# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod properties
mod_version = 3.1.1
maven_group = me.johnadept
archives_name = auto_attack
enabled_platforms = fabric,neoforge

# Mod Info
mod_id=auto_attack
mod_name=Auto Attack
mod_description=A mod that automatically strikes when the attack indicator is full.
mod_authors=John Adept
mod_license=MIT

# Minecraft properties
minecraft_version = 26.3

# Dependencies
architectury_api_version = 22.0.2
fabric_loader_version = 0.19.5
fabric_api_version = 0.161.0+26.3
neoforge_version = 26.3.0.6-beta
cloth_config_version = 26.3.158

# Fabric Only Dependencies
modmenu_version = 21.0.0-beta.1

# Neoforge Only Dependencies
